#!/bin/bash
set -euo pipefail

# Import MySQL orders.csv into PostgreSQL Docker container.
# Usage: ./scripts/import.sh orders.csv

CSV_FILE="${1:?Usage: $0 <orders.csv>}"
CONTAINER="${CONTAINER:-dujiao-order-db-1}"
DB_USER="${DB_USER:-dujiao}"
DB_NAME="${DB_NAME:-dujiao_order}"

if [ ! -f "$CSV_FILE" ]; then
    echo "Error: $CSV_FILE not found"
    exit 1
fi

echo "==> Ensuring database and table exist..."
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d postgres <<SQL
SELECT 'CREATE DATABASE $DB_NAME' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')\gexec
SQL

docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" < initdb/001_create_orders.sql

echo "==> Converting MySQL CSV to PostgreSQL format..."
python3 scripts/import_orders.py "$CSV_FILE" > /tmp/orders_pg.csv

echo "==> Copying CSV into container..."
docker cp /tmp/orders_pg.csv "$CONTAINER":/tmp/orders_pg.csv

echo "==> Importing into PostgreSQL..."
docker exec -i "$CONTAINER" psql -U "$DB_USER" -d "$DB_NAME" <<'SQL'
BEGIN;

-- Allow explicit id values during import
ALTER TABLE orders ALTER COLUMN id SET GENERATED BY DEFAULT;

\COPY orders(id,order_no,trade_no,pay_id,order_password,total_price,actual_price,goods_price,buy_amount,client_ip,email,info,status,gd_name,gp_name,coupon_id,coupon_discount,wholesale_discount,buy_limit_num,buy_prompt,created_at,updated_at) FROM '/tmp/orders_pg.csv' WITH (FORMAT csv, HEADER true, NULL '');

-- Restore identity column and reset sequence
ALTER TABLE orders ALTER COLUMN id SET GENERATED ALWAYS;
SELECT setval(pg_get_serial_sequence('orders', 'id'), (SELECT MAX(id) FROM orders));

COMMIT;

-- Verify
SELECT COUNT(*) AS total_rows FROM orders;
SELECT status, COUNT(*) FROM orders GROUP BY status ORDER BY count DESC;
SQL

echo "==> Done. Cleaning up..."
rm -f /tmp/orders_pg.csv
docker exec "$CONTAINER" rm -f /tmp/orders_pg.csv
echo "Import complete."
